### ISSUE TITLE
When creating an account I get this error

### ISSUE THREAD

**Issue by kolawoletech** [javebratt/project-planner#1]
Uncaught TypeError: Cannot read property 'active' of null
    at auth-data.ts:84
    at c (database.js:174)
    at database.js:165

**Comment by javebratt** [comment]
Please provide more information, like what are you trying to accomplish, where does the error come from, the full stack trace, etc.

Also, please note that this repository belongs to a paid product, all the instructions on how to use are in the [book](https://javebratt.com/ionic-firebase-book)
